---
- name: update software to latest
  apt: 
    update_cache: yes
    upgrade: dist

- name: restart to finish
  command: /sbin/reboot

#- name: Wait for the server to finish rebooting
#  sudo: no
#  local_action: wait_for host="{{ inventory_hostname }}" search_regex=OpenSSH port=2200 ti:meout=300
